sudo: required
language: python
# services:
#   - docker

# before_install:
#   - docker build -t warturtle/obscura6-frontend -f Dockerfile.dev .
# script:
#   - docker run warturtle/obscura6-frontend npm run test -- --coverage
script:
  - echo "success"

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
