sudo: required
language: python
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  - docker build -t warturtle/obscura6-frontend -f Dockerfile.dev .
script:
  - docker run warturtle/obscura6-frontend npm run test -- --coverage

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
